#!/bin/sh

root="$HOME/Backup"

for file in * ; do
    found="no"
    loc=""
    for ((year=2020; year>=2008; year--)) do
        for dir in "$@" ; do
            if test -e "$root/$year/$dir/$file" ; then
                if test "$found" = "no" ; then
                    found="old"
                    loc="$year ($dir)"
                fi
                if test "$found" = "old" && diff -r "$file" "$root/$year/$dir/$file" > /dev/null ; then
                    found="yes"
                    loc="$year ($dir)"
                fi
            fi
        done
    done
    case "$found" in
        "no" ) echo " ! $file" ;;
        "old" ) echo " * $file: $loc" ;;
        "yes" ) echo "   $file: $loc" ;;
    esac
done

echo
