#!/bin/bash

[[ -f ~/.profile ]] && . ~/.profile
[[ -f ~/.bashrc ]] && . ~/.bashrc

if [ -z "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ] && [ "$XDG_VTNR" = 1 ] && command -v labwc >/dev/null ; then
  exec labwc >"$XDG_RUNTIME_DIR"/labwc.log 2>&1
fi
