#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

if [[ "$TERM" == rxvt-unicode* ]]; then
    xseticon -id "$WINDOWID" /usr/share/icons/gnome/48x48/apps/utilities-terminal.png
    alias clear="echo -ne '\033c'" # clear scrollback
fi
