#!/bin/sh

export XSESSION_PID=$$

. ~/.config/xprofile
xrdb ~/.config/xresources
numlockx

xsettingsd -c ~/.config/xsettings &

/usr/lib/xfce4/notifyd/xfce4-notifyd &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

setup-desktop
srandrd setup-desktop

picom &
qmpanel &

exec openbox
