#!/bin/sh

systemctl --user import-environment

if test x"$XSESSION_STARTED" = x ; then
  exec systemd-run --user --wait -EXSESSION_STARTED=1 "$0"
fi

unset XSESSION_STARTED

export GTK_OVERLAY_SCROLLING=0
export QT_ENABLE_HIGHDPI_SCALING=0
export QT_LOGGING_RULES="*.debug=false"
export QT_QPA_PLATFORMTHEME=qt5ct
export SAL_USE_VCLPLUGIN=gtk

xrdb ~/.config/xresources
numlockx

xsettingsd -c ~/.config/xsettings &
setup-desktop
srandrd setup-desktop

compton &
qmpanel &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
cbatticon &
keepassxc &
nm-applet &
quick-settings &
volumeicon &
openbox

# kill uncooperative apps
pkill -kill nemo
