#!/bin/sh

export GTK_OVERLAY_SCROLLING=0
export QT_ENABLE_HIGHDPI_SCALING=0
export QT_FONT_DPI=128
export QT_LOGGING_RULES="*.debug=false"
export QT_QPA_PLATFORMTHEME=qt5ct
export SAL_USE_VCLPLUGIN=kf5
export XDG_CURRENT_DESKTOP=XFCE

xrdb ~/.config/xresources
numlockx

xsettingsd -c ~/.config/xsettings &

/usr/lib/xfce4/notifyd/xfce4-notifyd &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

setup-desktop
srandrd setup-desktop

picom --experimental-backends &
qmpanel &
cbatticon &
keepassxc &
nm-applet &
quick-settings &
volumeicon &

exec openbox
