#!/bin/sh

export GTK_OVERLAY_SCROLLING=0
export FREETYPE_PROPERTIES="cff:no-stem-darkening=0"
export QT_ENABLE_HIGHDPI_SCALING=0
export QT_FONT_DPI=128
export QT_LOGGING_RULES="*.debug=false"
export QT_QPA_PLATFORMTHEME=qt5ct
export SAL_USE_VCLPLUGIN=qt6
export XDG_CURRENT_DESKTOP=XFCE
