#!/bin/sh
if [ remove = "$1" -o abort-install = "$1" -o disappear = "$1" ]; then
  dpkg-divert --package config --remove --rename \
    --divert /etc/lightdm/lightdm-gtk-greeter.conf.orig /etc/lightdm/lightdm-gtk-greeter.conf
fi
