#!/bin/sh

export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true"
export FREETYPE_PROPERTIES="cff:no-stem-darkening=0"
export GTK_A11Y=none
export GTK_OVERLAY_SCROLLING=0
export NO_AT_BRIDGE=1
export QT_ENABLE_HIGHDPI_SCALING=0
export QT_FONT_DPI=${FONT_DPI}
export QT_LOGGING_RULES="*.debug=false"
export QT_QPA_PLATFORMTHEME=qt5ct
export SAL_USE_VCLPLUGIN=qt6
export XDG_CURRENT_DESKTOP=XFCE
